package com.gss.student.webservice;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 3/10/2015 1:30:14 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import java.util.Hashtable;

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class SemesterMarks implements KvmSerializable {
    
    public String mSemster;
    public int mPercent;
    public VectorSubjectMarks subjectMarkList;
    
    public SemesterMarks(){}
    
    public SemesterMarks(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("mSemster"))
        {
            Object obj = soapObject.getProperty("mSemster");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                mSemster = j.toString();
            }else if (obj!= null && obj instanceof String){
                mSemster = (String) obj;
            }
        }
        if (soapObject.hasProperty("mPercent"))
        {
            Object obj = soapObject.getProperty("mPercent");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                mPercent = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                mPercent = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("subjectMarkList"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("subjectMarkList");
            subjectMarkList = new VectorSubjectMarks(j);
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return mSemster;
            case 1:
                return mPercent;
            case 2:
                return subjectMarkList;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 3;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "mSemster";
                break;
            case 1:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "mPercent";
                break;
            case 2:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "subjectMarkList";
                break;
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
