package com.gss.student.webservice;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 3/5/2015 3:54:30 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import java.util.List;

import org.ksoap2.HeaderProperty;
import org.ksoap2.SoapEnvelope;
import org.ksoap2.SoapFault;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapSerializationEnvelope;
import org.ksoap2.transport.HttpTransportSE;

import android.os.AsyncTask;

import com.gss.student.webservice.WS_Enums.SoapProtocolVersion;

public class StudentDetails {
    
    public String NAMESPACE ="http://tempuri.org/";
    public String url="http://192.168.88.29:8080/webservices/StudentDetails.asmx";
    public int timeOut = 60000;
    public IWsdl2CodeEvents eventHandler;
    public SoapProtocolVersion soapVersion;
    
    public StudentDetails(){}
    
    public StudentDetails(IWsdl2CodeEvents eventHandler)
    {
        this.eventHandler = eventHandler;
    }
    public StudentDetails(IWsdl2CodeEvents eventHandler,String url)
    {
        this.eventHandler = eventHandler;
        this.url = url;
    }
    public StudentDetails(IWsdl2CodeEvents eventHandler,String url,int timeOutInSeconds)
    {
        this.eventHandler = eventHandler;
        this.url = url;
        this.setTimeOut(timeOutInSeconds);
    }
    public void setTimeOut(int seconds){
        this.timeOut = seconds * 1000;
    }
    public void setUrl(String url){
        this.url = url;
    }
    public void getStudentDetailsAsync(String studentRegNo) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        getStudentDetailsAsync(studentRegNo, null);
    }
    
    public void getStudentDetailsAsync(final String studentRegNo,final List<HeaderProperty> headers) throws Exception{
        
        new AsyncTask<Void, Void, VectorAbsentDetail>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected VectorAbsentDetail doInBackground(Void... params) {
                return getStudentDetails(studentRegNo, headers);
            }
            @Override
            protected void onPostExecute(VectorAbsentDetail result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("getStudentDetails", result);
                }
            }
        }.execute();
    }
    
    public VectorAbsentDetail getStudentDetails(String studentRegNo){
        return getStudentDetails(studentRegNo, null);
    }
    
    public VectorAbsentDetail getStudentDetails(String studentRegNo,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("http://tempuri.org/","getStudentDetails");
        soapReq.addProperty("studentRegNo",studentRegNo);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("http://tempuri.org/getStudentDetails", soapEnvelope,headers);
            }else{
                httpTransport.call("http://tempuri.org/getStudentDetails", soapEnvelope);
            }
            Object retObj = soapEnvelope.bodyIn;
            if (retObj instanceof SoapFault){
                SoapFault fault = (SoapFault)retObj;
                Exception ex = new Exception(fault.faultstring);
                if (eventHandler != null)
                    eventHandler.Wsdl2CodeFinishedWithException(ex);
            }else{
                SoapObject result=(SoapObject)retObj;
                if (result.getPropertyCount() > 0){
                    Object obj = result.getProperty(0);
                    SoapObject j = (SoapObject)obj;
                    VectorAbsentDetail resultVariable = new VectorAbsentDetail(j);
                    return resultVariable;
                }
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
        return null;
    }
    
    public void getMarksAsync(String studentRegNo) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        getMarksAsync(studentRegNo, null);
    }
    
    public void getMarksAsync(final String studentRegNo,final List<HeaderProperty> headers) throws Exception{
        
        new AsyncTask<Void, Void, VectorSemesterMarks>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected VectorSemesterMarks doInBackground(Void... params) {
                return getMarks(studentRegNo, headers);
            }
            @Override
            protected void onPostExecute(VectorSemesterMarks result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("getMarks", result);
                }
            }
        }.execute();
    }
    
    public VectorSemesterMarks getMarks(String studentRegNo){
        return getMarks(studentRegNo, null);
    }
    
    public VectorSemesterMarks getMarks(String studentRegNo,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("http://tempuri.org/","getMarks");
        soapReq.addProperty("studentRegNo",studentRegNo);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("http://tempuri.org/getMarks", soapEnvelope,headers);
            }else{
                httpTransport.call("http://tempuri.org/getMarks", soapEnvelope);
            }
            Object retObj = soapEnvelope.bodyIn;
            if (retObj instanceof SoapFault){
                SoapFault fault = (SoapFault)retObj;
                Exception ex = new Exception(fault.faultstring);
                if (eventHandler != null)
                    eventHandler.Wsdl2CodeFinishedWithException(ex);
            }else{
                SoapObject result=(SoapObject)retObj;
                if (result.getPropertyCount() > 0){
                    Object obj = result.getProperty(0);
                    SoapObject j = (SoapObject)obj;
                    VectorSemesterMarks resultVariable = new VectorSemesterMarks(j);
                    return resultVariable;
                }
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
        return null;
    }
    
}
