package com.gss.student.webservice;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 3/10/2015 1:30:14 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class SubjectMarks implements KvmSerializable {
    
    public String mSubjectCode;
    public String mSubjectName;
    public int mMarks;
    
    public SubjectMarks(){}
    
    public SubjectMarks(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("mSubjectCode"))
        {
            Object obj = soapObject.getProperty("mSubjectCode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                mSubjectCode = j.toString();
            }else if (obj!= null && obj instanceof String){
                mSubjectCode = (String) obj;
            }
        }
        if (soapObject.hasProperty("mSubjectName"))
        {
            Object obj = soapObject.getProperty("mSubjectName");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                mSubjectName = j.toString();
            }else if (obj!= null && obj instanceof String){
                mSubjectName = (String) obj;
            }
        }
        if (soapObject.hasProperty("mMarks"))
        {
            Object obj = soapObject.getProperty("mMarks");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                mMarks = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                mMarks = (Integer) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return mSubjectCode;
            case 1:
                return mSubjectName;
            case 2:
                return mMarks;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 3;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "mSubjectCode";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "mSubjectName";
                break;
            case 2:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "mMarks";
                break;
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
